### ISSUE TITLE
how to upgrade to @1.0.0-beta.11

### ISSUE THREAD

**Issue by welkinwong** [share/sharedb-mongo#84]
when i upgrade to @1.0.0-beta.11 
`TypeError: client.db is not a function`

code:
`const backend = new ShareDB({
  db: shareDbMongo({
    mongo (callback) {
      callback(null, MongoInternals.defaultRemoteCollectionDriver().mongo.db);
    },
  }),
  disableDocAction: true,
  disableSpaceDelimitedActions: true,
});`

but it work on @1.0.0-beta.9

**Comment by welkinwong** [comment]
same

**Comment by ericyhwang** [comment]
If your service is using the Mongo 3.x driver, then pass sharedb-mongo a `mongodb.MongoClient`, not a `mongodb.Db`.

Reason is because in Mongo driver 3.x, the `Db` class no longer has a `close()` method, which sharedb-mongo needs to call when it's closing.

In your example, you may need to add a new `.client` property to your code, so that you can do `MongoInternals.defaultRemoteCollectionDriver().mongo.client`.

**Comment by ericyhwang** [comment]
I added a note about it to the 1.0.0-beta.11 release notes. Thank you for flagging it!

**Comment by welkinwong** [comment]
> If your service is using the Mongo 3.x driver, then pass sharedb-mongo a `mongodb.MongoClient`, not a `mongodb.Db`.
> 
> Reason is because in Mongo driver 3.x, the `Db` class no longer has a `close()` method, which sharedb-mongo needs to call when it's closing.
> 
> In your example, you may need to add a new `.client` property to your code, so that you can do `MongoInternals.defaultRemoteCollectionDriver().mongo.client`.

WoW
It Works
thankyou!!!
